/*
 * This file is generated by jOOQ.
*/
package shapedirection.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import shapedirection.jooq.tables.Peers;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cryptoputty extends SchemaImpl {

    private static final long serialVersionUID = -1173909263;

    /**
     * The reference instance of <code>cryptoputty</code>
     */
    public static final Cryptoputty CRYPTOPUTTY = new Cryptoputty();

    /**
     * The table <code>cryptoputty.peers</code>.
     */
    public final Peers PEERS = shapedirection.jooq.tables.Peers.PEERS;

    /**
     * No further instances allowed
     */
    private Cryptoputty() {
        super("cryptoputty", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Peers.PEERS);
    }
}
