/*
 * This file is generated by jOOQ.
*/
package shapedirection.jooq;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import shapedirection.jooq.tables.Peers;


/**
 * A class modelling indexes of tables of the <code>cryptoputty</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PEERS_PRIMARY = Indexes0.PEERS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PEERS_PRIMARY = Internal.createIndex("PRIMARY", Peers.PEERS, new OrderField[] { Peers.PEERS.ID }, true);
    }
}
