/*
 * This file is generated by jOOQ.
*/
package shapedirection.jooq;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import shapedirection.jooq.tables.Peers;
import shapedirection.jooq.tables.records.PeersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>cryptoputty</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PeersRecord, Long> IDENTITY_PEERS = Identities0.IDENTITY_PEERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PeersRecord> KEY_PEERS_PRIMARY = UniqueKeys0.KEY_PEERS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<PeersRecord, Long> IDENTITY_PEERS = Internal.createIdentity(Peers.PEERS, Peers.PEERS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<PeersRecord> KEY_PEERS_PRIMARY = Internal.createUniqueKey(Peers.PEERS, "KEY_peers_PRIMARY", Peers.PEERS.ID);
    }
}
