/*
 * This file is generated by jOOQ.
*/
package shapedirection.jooq;


import javax.annotation.Generated;

import shapedirection.jooq.tables.Peers;


/**
 * Convenience access to all tables in cryptoputty
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cryptoputty.peers</code>.
     */
    public static final Peers PEERS = shapedirection.jooq.tables.Peers.PEERS;
}
